### ISSUE TITLE
Include the Other Stats

### ISSUE THREAD

**Issue by kylewilliams321** [jcgoette/weight_gurus_homeassistant#2]
Having this integration is going to be great. Thanks for doing it.

A couple of requests:
Can we get a lovelace card that shows history and progress towards your weight goal. Could customize it to show weekly or monthly or maybe even daily tracking? 
Thoughts?
Would be cool to include the other stats as well as weight like BMI, body_fat, water!

THANKS!

**Comment by jcgoette** [comment]
- Can we get a lovelace card that shows history and progress towards your weight goal. Could customize it to show weekly or monthly or maybe even daily tracking?
  - Hmm. Do you mean the weight goal listed in Weight Gurus? Will have to see if that is exposed via API. If so, I think this could be created with HA built-in tools.
- Would be cool to include the other stats as well as weight like BMI, body_fat, water!
  - Will work on this.

**Comment by kylewilliams321** [comment]
@jcgoette - yea I mean clearly this isn't very helpful...
![image](https://user-images.githubusercontent.com/39958233/141838441-1d0dc59f-b0f1-4c35-8d7e-7cca41e776b2.png)

Im just looking for something a little more user friendly and something that shows useful data. Thanks!

**Comment by jcgoette** [comment]
Got it. I think this will work better if we update this integration to allow HA to provide [long-term statistics](https://developers.home-assistant.io/blog/2021/05/25/sensor_attributes/).

Also, it looks like goal weight is provided in account level JSON under key `goalWeight`.

I will start work on updating integration soon-ish.
